### ISSUE TITLE
Command on away/back

### ISSUE THREAD

**Issue by AeliusSaionji** [jcvernaleo/tmux_away#1]
Feature request :)

**Comment by jcvernaleo** [comment]
@Aelius-Saionji I probably won't get a chance to do anything until this weekend, but I like that idea and think it should be very doable.

**Comment by AeliusSaionji** [comment]
No problem, take your time

**Comment by jcvernaleo** [comment]
@Aelius-Saionji check out the latest master commit d83f11fc4410f4c28b93bd7c949442fb37dc5ac1

Does that do what you were asking?

**Comment by AeliusSaionji** [comment]
I'm extremely embarrassed but the reason I wanted this was so I could change my nick only while I was connected. And now I see that's already a feature... :D sorry.

**Comment by AeliusSaionji** [comment]
Wait no I remember what I wanted this for- I wanted to part a channel on away and rejoin it on back- if you would please add a disconnect command as well as the reconnect command. Thank you

**Comment by jcvernaleo** [comment]
@Aelius-Saionji  Check out the latest commit on master.  I think that takes care of the case you bring up (but let me know if it doesn't).
